ip_domain_name: from_r2_hostvar.com
dc1_domain: dc_from_r2.com
interface_list:
  - name: GigabitEthernet0/2
    description: Gi2_descript
    ip: 100.1.2.2
    mask: 255.255.255.0
  - name: GigabitEthernet0/3
    description: Gi3_descript
    ip: 100.1.3.3
    mask: 255.255.255.0
  - name: GigabitEthernet0/4
    description: Gi4_descript
# dest_subs:
#   - 10.1.1.0
#   - 10.1.2.0
#   - 10.1.3.0
#   - 10.1.4.0
#   - 10.1.5.0

# dest_gws:
#   - 100.1.1.1
#   - 100.1.1.2
#   - 100.1.1.3
#   - 100.1.1.4
  # - 100.1.1.5
